# Generated by Django 5.1.6 on 2025-06-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        ('stock', '0002_depositos_stockproductos_delete_stock'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitos',
            name='deposito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.depositos'),
        ),
        migrations.AddField(
            model_name='remitos',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='remitoproducto',
            name='remito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingresos.remitos'),
        ),
    ]
