# Generated by Django 5.2.1 on 2025-06-26 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remitos',
            name='deposito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.depositos'),
        ),
        migrations.AddField(
            model_name='remitos',
            name='productos',
            field=models.ManyToManyField(through='ingresos.RemitoProducto', to='ingresos.productos'),
        ),
        migrations.AddField(
            model_name='remitos',
            name='usuario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remitoproducto',
            name='remito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.remitos'),
        ),
    ]
