# Generated by Django 5.2.1 on 2025-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
