# Generated by Django 5.2.1 on 2025-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remitos",
            name="aprobado",
            field=models.BooleanField(),
        ),
    ]
