# Generated by Django 5.2.1 on 2025-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remitos',
            name='aprobado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='remitos',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
