# Generated by Django 5.2.1 on 2025-06-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0003_alter_remitos_aprobado"),
        ("ingresos", "0003_alter_remitos_aprobado_alter_remitos_fecha_ingreso"),
    ]

    operations = []
