# Generated by Django 5.2.1 on 2025-06-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_merge_20250605_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitos',
            name='productos',
            field=models.ManyToManyField(through='ingresos.RemitoProducto', to='ingresos.productos'),
        ),
        migrations.AlterField(
            model_name='remitoproducto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='remitoproducto',
            name='remito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.remitos'),
        ),
    ]
