# Generated by Django 5.1.6 on 2025-06-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=20, unique=True)),
                ('fecha_alta', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialOrdenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_detectada', models.CharField(max_length=50)),
                ('reparacion', models.CharField(max_length=50)),
                ('fecha_revision', models.DateTimeField()),
                ('orden_activa', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.destinos')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.equipos')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.estados')),
                ('modificacion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.historialordenes')),
                ('remito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.remitos')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
