# Generated by Django 5.2.1 on 2025-06-13 23:37

import apps.ordenes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialOrdenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_detectada', models.CharField(blank=True, max_length=50, null=True)),
                ('reparacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('orden_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo_palletizado', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.destinos')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_editando', to=settings.AUTH_USER_MODEL)),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.equipos')),
                ('estado_id', models.ForeignKey(default=apps.ordenes.models.get_estado_pendiente, on_delete=django.db.models.deletion.CASCADE, to='ordenes.estados')),
                ('modificacion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.historialordenes')),
                ('remito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.remitos')),
            ],
        ),
    ]
