# Generated by Django 5.2.1 on 2025-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='equipo_palletizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_revision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='orden_activa',
            field=models.BooleanField(default=True),
        ),
    ]
