# Generated by Django 5.2.1 on 2025-06-18 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='palletizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_palletizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='usuario',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.estados'),
        ),
    ]
