# Generated by Django 5.2.1 on 2025-06-09 02:33

import apps.ordenes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_ordenes_equipo_palletizado_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_editando', to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='estado_id',
            field=models.ForeignKey(default=apps.ordenes.models.get_estado_pendiente, on_delete=django.db.models.deletion.CASCADE, to='ordenes.estados'),
        ),
    ]
