# Generated by Django 5.2.1 on 2025-06-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_merge_20250605_1449'),
        ('ordenes', '0003_remove_ordenes_usuario_id_ordenes_editado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.productos'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.destinos'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='falla_detectada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='reparacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
