# Generated by Django 5.2.1 on 2025-06-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_equipos_producto_id_alter_ordenes_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialordenes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialordenes',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
