# Generated by Django 5.2.1 on 2025-06-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.depositos')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.productos')),
            ],
        ),
    ]
