# Generated by Django 5.1.6 on 2025-06-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField()),
                ('deposito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.depositos')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.productos')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
