# Generated by Django 5.2.1 on 2025-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_depositos_stockproductos_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproductos',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockproductos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
