# Generated by Django 5.2.3 on 2025-06-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingresos", "0004_remove_remitos_usuario_id_remitos_usuario_and_more"),
        ("ordenes", "0002_ordenes_palletizado_por_ordenes_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_pallet",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("nro_viaje", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_despacho", models.DateTimeField(blank=True, null=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets_despacho",
                        to="ordenes.destinos",
                    ),
                ),
                (
                    "remito_salida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingresos.remitos",
                    ),
                ),
                (
                    "usuario_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pallet de Despacho",
                "verbose_name_plural": "Pallets de Despacho",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetallePallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("serial", models.CharField(blank=True, max_length=100, null=True)),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "orden_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalle_pallet",
                        to="ordenes.ordenes",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="despachos.pallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pallet",
                "verbose_name_plural": "Detalles de Pallets",
                "unique_together": {("pallet", "orden_id")},
            },
        ),
    ]
