# Generated by Django 5.2.1 on 2025-06-26 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingresos", "0002_initial"),
        ("ordenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_pallet",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Pallet",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Última Modificación"
                    ),
                ),
                (
                    "nro_viaje",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Viaje",
                    ),
                ),
                (
                    "fecha_despacho",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Despacho"
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets_despacho",
                        to="ordenes.destinos",
                        verbose_name="Destino",
                    ),
                ),
                (
                    "estado_pallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets_por_estado",
                        to="ordenes.estados",
                        verbose_name="Estado del Pallet",
                    ),
                ),
                (
                    "remito_salida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ingresos.remitos",
                        verbose_name="Remito de Salida",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_despacho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pallets_despachados_por_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Despachó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pallet de Despacho",
                "verbose_name_plural": "Pallets de Despacho",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetallePallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_pallet_asociado",
                        to="ordenes.ordenes",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="despachos.pallet",
                        verbose_name="Pallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pallet",
                "verbose_name_plural": "Detalles de Pallet",
                "unique_together": {("pallet", "orden_id")},
            },
        ),
    ]
