# Generated by Django 5.2.3 on 2025-06-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despachos", "0001_initial"),
        ("ordenes", "0002_ordenes_palletizado_por_ordenes_usuario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detallepallet",
            options={
                "verbose_name": "Detalle de Pallet",
                "verbose_name_plural": "Detalles de Pallet",
            },
        ),
        migrations.AddField(
            model_name="pallet",
            name="estado_pallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pallets_por_estado",
                to="ordenes.estados",
            ),
        ),
        migrations.AlterField(
            model_name="detallepallet",
            name="cantidad",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="detallepallet",
            name="orden_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_pallet",
                to="ordenes.ordenes",
            ),
        ),
    ]
