# Generated by Django 5.2.1 on 2025-06-26 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despachos", "0002_alter_detallepallet_options_pallet_estado_pallet_and_more"),
        ("ingresos", "0004_remove_remitos_usuario_id_remitos_usuario_and_more"),
        ("ordenes", "0002_ordenes_palletizado_por_ordenes_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallepallet",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="detallepallet",
            name="modelo",
        ),
        migrations.RemoveField(
            model_name="detallepallet",
            name="serial",
        ),
        migrations.RemoveField(
            model_name="pallet",
            name="usuario_id",
        ),
        migrations.AddField(
            model_name="pallet",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Última Modificación"
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="usuario",
            field=models.ForeignKey(
                default=2,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pallet",
            name="usuario_despacho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallets_despachados_por_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que Despachó",
            ),
        ),
        migrations.AlterField(
            model_name="detallepallet",
            name="orden_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_pallet_asociado",
                to="ordenes.ordenes",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="detallepallet",
            name="pallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="despachos.pallet",
                verbose_name="Pallet",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pallets_despacho",
                to="ordenes.destinos",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="estado_pallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pallets_por_estado",
                to="ordenes.estados",
                verbose_name="Estado del Pallet",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="fecha_despacho",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Despacho"
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="nro_pallet",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número de Pallet",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="nro_viaje",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Viaje"
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="remito_salida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingresos.remitos",
                verbose_name="Remito de Salida",
            ),
        ),
    ]
